name: conditionalWorkflow
on: 
  push:
    branches:
      - master

jobs:
    Lint:
      outputs:
        LintSuccess: ${{steps.lint.outputs.LintSuccess}}
      strategy:
        matrix:
          os: [ubuntu-latest,windows-latest]
      runs-on: ${{matrix.os}}
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Get Node
          uses: actions/setup-Node@v3
          with:
            node-version: '18'
        - name: cache Node module
          id: cache-u
          uses: actions/cache@v3
          with:
            path: node_modules
            key:  node-module-${{ hashFiles('package-lock.json') }}
        - name: install dependencie
          if: steps.cache-u.outputs.cache-hit =='false'
          run: npm ci
        - name: Run Lint
          id:  lint
          run: |
            npm run lint
            echo "LintSuccess=True" >> $GITHUB_OUTPUT
    Message:
      needs: [Lint]
      if: needs.Lint.outputs.LintSuccess == 'True'
      runs-on: ubuntu-latest
      steps:
        - name: Message
          run: echo Lint Success
    Test:
      uses: ./.github/workflows/reusable-code.yaml
    Message2:
      needs: [Test]
      if:  success()
      runs-on: ubuntu-latest
      steps:
        - name: Print Outcome 
          run: echo "${{needs.Test.outputs.TestRunOutcome}}"
        - name: Print conclusion
          run:  echo "${{needs.Test.outputs.TestRunConclusion}}"