name: envExample
on:
  workflow_dispatch:
env:
  DAY: Monday
jobs:
  Greeting:
    environment: test
    env:
      MONTH: ${{vars.MONTH}}
      YEAR: ${{secrets.YEAR}}
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "'$DAY'/ ${{env.MONTH}} / ${{env.YEAR}}"

        
