name: Get Code and Use cache
on: 
  workflow_call:
    outputs:
      TestRunOutcome:
        value: ${{jobs.Test.outputs.TestRunOutcome}}
      TestRunConclusion: 
        value: ${{jobs.Test.outputs.TestRunConclusion}}
jobs:
  Test:
    outputs:
        TestRunOutcome: ${{steps.capture.outputs.TestRunStatus}}
        TestRunConclusion: ${{steps.capture.outputs.TestRunCon}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get Node
        uses: actions/setup-Node@v3
        with:
          node-version: '18'
      - name: Get Cache
        id: cache-u
        uses: actions/cache@v3
        with:
          path: node_modules
          key:  node-module-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-u.outputs.cache-hit=='false'
        run: npm ci
      - name: Run Test
        id: testRun
        continue-on-error: true
        run: npm run test
      - name: Capture TestRunStatu
        id: capture
        run: |
           echo "TestRunStatus=${{steps.testRun.outcome}}" >> $GITHUB_OUTPUT
           echo "TestRunCon=${{steps.testRun.conclusion}}" >> $GITHUB_OUTPUT
